services:
  database:
    image: "postgres:16.0-alpine3.18"
    ports:
      - "5432:5432"
    env_file:
      - ../.env.development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
