services:
  database:
    image: "postgres:16.0-alpine3.18"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hackclub
